### PR TITLE
Address clippy lints

### PR DESCRIPTION
**Pull request by robjtede**

### CODE REVIEW

**Review by dconnolly — APPROVED** [review]

**Comment by pinkforest** [comment]
@robjtede thanks :sweat_smile: 

Could we also include `--all-features` as well in:
https://github.com/dalek-cryptography/curve25519-dalek/blob/main/.github/workflows/workspace.yml#L68

**Comment by robjtede** [comment]
@pinkforest bump on this since it LG now

**Comment by robjtede** [comment]
bump, this an easy enough merge

**Review by tarcieri — APPROVED** [review]
I might suggest disabling `clippy::needless_range_loop` but this is otherwise fine

**Pull request merged**
