### PR TITLE
Implement Product and Sum traits

### LINKED ISSUE #131: Iterators should implement `Sum` and `Product`
Rust defines [`Sum`]( https://doc.rust-lang.org/std/iter/trait.Sum.html) and [`Product`](https://doc.rust-lang.org/std/iter/trait.Product.html) traits that allow sums and products of iterators.

I think it makes sense to implement:

- [ ] `impl Sum for RistrettoPoint`
- [ ] `impl Sum for EdwardsPoint`
- [ ] `impl Sum for Scalar`
- [ ] `impl Product for Scalar`

These can be implemented using `fold` internally.

### PR DESCRIPTION
**Pull request by Mandragorian**
This PR implements the [Product](https://doc.rust-lang.org/std/iter/trait.Product.html) and [Sum](https://doc.rust-lang.org/std/iter/trait.Sum.html) traits for Scalar.

Partially resolves #131 

I made this PR before implement the Sum trait on the other types so that you can comment on my code before trying to implement the other traits. If you would like me completely close issue #131 before making a PR just tell me.

### CODE REVIEW

**Comment by hdevalence** [comment]
This looks great, especially the point tests are well-done! 

The only change I would ask for is to just implement the point types directly, rather than using a macro.  The reason is that the macro adds an extra layer of complexity, but there are only two point types and we don't have any plans to add more.

**Comment by Mandragorian** [comment]
Ok, moved the definitions in each file and removed the commit introducing the macro.

**Comment by hdevalence** [comment]
Thanks! The CI is failing for what looks like an unrelated reason. I'll try to fix it, then review your PR.

**Comment by hdevalence** [comment]
(The CI failure is an unrelated issue in today's nightly cargo related to optional dependencies, and all of the other tests pass).

This looks great! Thanks a lot for the PR.

**Pull request merged**
