### PR TITLE
Fix all clippy warnings

### PR DESCRIPTION
**Pull request by nox**

### CODE REVIEW

**Comment by rozbb** [comment]
Thank you for this! It might be a bit premature, since we have some rustfmt PRs we need to get through first. If you're able to rebase, I can let you know what to rebase on when it lands.

**Comment by rozbb** [comment]
Could you rebase when you get a chance? This all looks great!

**Comment by pinkforest** [comment]
@rozbb could we get the doc stuff merged into release and I could then replay these changes and make sure @nox gets credit w/ Co-authored by commit ?

**Comment by rozbb** [comment]
Done

**Comment by pinkforest** [comment]
#441 replays this re-based

**Comment by rozbb** [comment]
Resolved by #441

**Pull request closed without merging**
