### PR TITLE
Docs include README

### LINKED ISSUE #426: Use `#![doc = include_str!("../README.md")]`
`src/lib.rs` contains large blocks of copy/paste from README.md.

The `#![doc = include_str!("../README.md")]` directive can be used to include the README.md in the rustdoc, eliminating the duplication, and ensuring all code examples in README.md are also doctested.

### PR DESCRIPTION
**Pull request by pinkforest**
Fixes #426 

@tarcieri will affect #428 for src/lib.rs changes

### CODE REVIEW

**Comment by pinkforest** [comment]
Before

$ cargo +nightly tarpaulin --run-types Tests,Doctests,Benchmarks,Examples,Lib,Bins
```
|| src/lib.rs: 8/21
|| src/macros.rs: 16/27
|| src/montgomery.rs: 80/90
|| src/ristretto.rs: 197/271
|| src/scalar.rs: 248/287
|| src/traits.rs: 19/20
|| src/window.rs: 48/72
|| 
56.04% coverage, 1587/2832 lines covered
```

After
```
TBD: Running ...
```

**Comment by pinkforest** [comment]
I wonder if these are more of manifest thing now ? if not then need to host the html logo somewhere I guess :thinking: 

```
#![doc(html_logo_url = "https://doc.dalek.rs/assets/dalek-logo-clear.png")]
#![doc(html_root_url = "https://docs.rs/curve25519-dalek/4.0.0-pre.2")]
```

**Comment by rozbb** [comment]
Yeah we gotta figure out where this will be hosted soon. Regardless, looks good. Thank you!

**Comment by rozbb** [comment]
Btw I'm gonna try soon to push some docs fixes I've had sitting around on my machine. They're out of date so I'll have to resolve some conflicts first.

**Comment by pinkforest** [comment]
Could use github.io static pages ? e.g. dalek-cryptography and then a new repo like "dalek-web" ?

**Comment by rozbb** [comment]
Yup, we might end up doing that. It'd be even nicer if we got docs.rs working, which #423 alleges will work

**Comment by pinkforest** [comment]
I have a feeling it needs more docsrs related meta: https://github.com/dalek-cryptography/curve25519-dalek/issues/341#issuecomment-1305727241

Aso need to refactor the current `#[cfg(rustdoc)]` around to fit the cfg that is used for docsrs now.

Lmk when you've pushed your docs fixes so I can work on top of that

**Comment by rozbb** [comment]
Will do!

**Comment by pinkforest** [comment]
btw #426 can be closed now :tada:

**Comment by rozbb** [comment]
Sorry for the delay. The `docs-cleanup` branch should have my (small) Markdown fixes

**Pull request merged**
