### PR TITLE
Bump to 0.4.0 criterion

### LINKED ISSUE #430: Duplicate `itoa` 0.4 via `csv` dev-dependency
`csv` has not had a release for a year and it's stuck at 0.4 itoa that uses unsound `std::mem::uninitialized`

https://github.com/BurntSushi/rust-csv/issues/271

This causes `itoa` dependency duplication

This is brought by `criterion` dev-dependency
```
 cargo tree -i csv
csv v1.1.6
└── criterion v0.3.6
    [dev-dependencies]
    └── curve25519-dalek v4.0.0-pre.2 (/home/foobar/pp/curve25519-dalek)
```

Currently `criterion` v0.3.6 is used and v0.4.0 is the latest

Looking at the `criterion` crate the `csv` dependency is optional in 0.4.0
`csv` crate used to be non-optional and default dependency in 0.3.6

So bumping up `criterion` will solve this.

```
warning[B004]: found 2 duplicate entries for crate 'itoa'
   ┌─ /home/foobar/pp/curve25519-dalek/Cargo.lock:30:1
   │  
30 │ ╭ itoa 0.4.8 registry+https://github.com/rust-lang/crates.io-index
31 │ │ itoa 1.0.4 registry+https://github.com/rust-lang/crates.io-index
   │ ╰────────────────────────────────────────────────────────────────^ lock entries
   │  
   = itoa v0.4.8
     └── csv v1.1.6
         └── criterion v0.3.6
             └── (dev) curve25519-dalek v4.0.0-pre.2
   = itoa v1.0.4
     └── serde_json v1.0.87
         ├── criterion v0.3.6
         │   └── (dev) curve25519-dalek v4.0.0-pre.2
         └── tinytemplate v1.2.1
             └── criterion v0.3.6 (*)
```

### LINKED ISSUE #431: Unmaintained `serde_cbor`
Crate `serder_cbor` is unmaintained

```
warning[A003]: serde_cbor is unmaintained
   ┌─ /home/foobar/pp/curve25519-dalek/Cargo.lock:60:1
   │
60 │ serde_cbor 0.11.2 registry+https://github.com/rust-lang/crates.io-index
   │ ----------------------------------------------------------------------- unmaintained advisory detected
   │
   = ID: RUSTSEC-2021-0127
   = Advisory: https://rustsec.org/advisories/RUSTSEC-2021-0127
   = The `serde_cbor` crate is unmaintained. The author has archived the github repository.
     
     Alternatives proposed by the author:
     
      * [`ciborium`](https://crates.io/crates/ciborium)
      * [`minicbor`](https://crates.io/crates/minicbor)
   = Announcement: https://github.com/pyfisch/cbor
   = Solution: No safe upgrade is available!
   = serde_cbor v0.11.2
     └── criterion v0.3.6
         └── (dev) curve25519-dalek v4.0.0-pre.2
```

### PR DESCRIPTION
**Pull request by pinkforest**
Fixes #430 and gets rid of the `csv` dependency that will get rid of the `itoa` 0.4 that used `mem::unitialized`
Fixes #431 and switches from unmaintained `serde_cbor` to `ciborium`

### CODE REVIEW

**Comment by pinkforest** [comment]
$ cargo +nightly tarpaulin --run-types Tests,Doctests,Benchmarks,Examples,Lib,Bins
```
Nov 11 23:33:11.669  INFO cargo_tarpaulin::report: Coverage Results:
|| Uncovered Lines:
|| benches/dalek_benchmarks.rs: 95-96, 103, 106, 125, 128, 149-150, 152, 180-181, 208-209, 266, 268, 271, 326, 328-329
|| src/backend/serial/curve_models/mod.rs: 189-192, 210-214, 246-247, 291, 293-296, 309, 311-313, 525-526, 529, 535-536, 539, 545-546, 549, 555-557
|| src/backend/serial/fiat_u32/field.rs: 72-76, 82-87, 92-96, 102-107, 112-114, 120-123, 129-134
|| src/backend/serial/fiat_u64/field.rs: 61-65, 71-76, 81-85, 91-96, 101-103, 109-112, 118-123, 183-186
|| src/backend/serial/scalar_mul/pippenger.rs: 150
|| src/backend/serial/scalar_mul/straus.rs: 142
|| src/backend/serial/u32/field.rs: 68-70, 77-80, 85, 89-100, 102, 108-111, 116-118, 126, 129-131, 135-136, 152, 156-157, 182-184, 186-195, 224, 230-233, 345-347, 349-350, 353-354, 408-409, 413-414, 570-571
|| src/backend/serial/u32/scalar.rs: 51-52, 212-213, 241-245, 248-252, 264, 270-279, 283-299, 306, 308-311, 314-317, 321, 324-332, 335-343, 346, 351-353, 359-361, 366-367, 372-373, 378-379
|| src/backend/serial/u64/field.rs: 45-46, 51-52, 69, 74-76, 103-105, 116, 219, 238-243, 292, 462
|| src/backend/serial/u64/scalar.rs: 27-28, 53, 200, 213, 219, 243, 245-246, 251-252, 281-282, 289-290, 296, 302
|| src/backend/vector/avx2/edwards.rs: 235-237, 245, 252, 254, 258, 261, 264, 267, 269, 274, 286-287, 292-296, 298, 303-308, 311, 316-321, 324
|| src/backend/vector/avx2/field.rs: 61-64, 68-69, 71, 84, 92-93, 98, 211-213, 217-227, 232, 236-241, 251-253, 277-279, 281-282, 284-285, 288-289, 292-293, 296-297, 300-301, 305-307, 314-319, 377, 381-386, 400, 402, 404, 406, 415-416, 418-425, 434, 439-440, 458, 461, 465, 467-468, 470-471, 473-474, 476-477, 479-480, 491, 497, 501, 505, 514, 524, 526-527, 530-532, 534-535, 538-539, 544-547, 550, 561-562, 568, 584-589, 605, 607, 611, 613, 708-714, 724-730, 743, 747, 749-753, 755-765, 786-788, 790, 793-794, 796, 799-803, 805-809, 811, 816-821, 825-827, 829-838, 878
|| src/backend/vector/ifma/edwards.rs: 129-130, 132, 135, 138, 141, 144, 146, 150, 179-181, 189-190, 195-199, 201, 206-211, 214, 219-224, 227
|| src/backend/vector/ifma/field.rs: 21, 23, 28, 30, 56, 60-70, 86, 90-96, 156, 158, 160, 162, 166-174, 179-185, 190-196, 214-222, 227-234, 240-246, 251-257, 262, 264, 267-275, 278-284, 286-287, 289-291, 293-296, 298-302, 304-309, 311-316, 318-322, 324-327, 329-331, 333-334, 336-339, 341-343, 345-346, 348-351, 353-357, 359-363, 365-370, 378-379, 385-387, 390-394, 397-402, 411-417, 425, 427, 429-432, 434, 436-445, 448-455, 458-460, 462-467, 476, 479-480, 483-491, 494-503, 511-518, 521-528, 531-538, 540-541, 544-551, 553-554, 557-564, 566, 569-576, 578-580, 583-590, 593-600, 603-604, 606-611
|| src/backend/vector/scalar_mul/pippenger.rs: 37-42, 44, 47-48, 53, 55, 57, 59-61, 66-67, 70, 72-73, 80, 82-88, 100-105, 108, 113, 116-118, 120
|| src/backend/vector/scalar_mul/precomputed_straus.rs: 39, 59, 61, 63, 65, 68, 70, 73-76, 81-83, 85-90, 94-99, 104
|| src/backend/vector/scalar_mul/straus.rs: 49, 51, 54, 56, 59, 61-65, 67, 70, 83, 85, 87, 89, 92, 94-95, 97-101, 106
|| src/edwards.rs: 166-167, 172-173, 232-234, 236, 247-249, 251, 263-264, 266-267, 270, 274-278, 280, 282, 286, 298-299, 301-302, 305, 309-313, 315, 319, 351-352, 362-363, 365, 367, 383-384, 394-396, 402-406, 613-614, 803, 850-851, 956-959, 961, 985-986, 991-992, 1094-1095, 1098
|| src/lib.rs: 247-249, 262, 267, 275, 281, 284, 288-289, 294
|| src/macros.rs: 9-10, 26-27, 42, 56-57, 63-64, 81-82
|| src/montgomery.rs: 84-85, 105-106, 112-113, 217-218, 347-348
|| src/ristretto.rs: 219-220, 226-227, 240-241, 243, 245, 306, 325-326, 350-352, 354, 365-367, 369, 381-382, 384-385, 388, 392-396, 398, 400, 404, 416-417, 419-420, 423, 427-431, 433, 437, 537, 543, 564, 774-775, 827-828, 837-838, 849-850, 885-887, 994, 1001, 1006, 1045-1046, 1050-1051, 1098-1099, 1104-1106, 1119-1120, 1125-1126
|| src/scalar.rs: 265-266, 327-328, 336-337, 352, 354, 367, 380-383, 401-403, 405, 417-418, 420-421, 424, 428-432, 434-435, 440, 469-470, 540-541, 971, 975, 1004-1005, 1010
|| src/traits.rs: 342
|| src/window.rs: 83-84, 86-87, 90, 153-154, 171-175, 178, 196-199, 201, 206-210, 213
|| Tested/Total Lines:
|| benches/dalek_benchmarks.rs: 140/159
|| src/backend/serial/curve_models/mod.rs: 111/143
|| src/backend/serial/fiat_u32/field.rs: 0/35
|| src/backend/serial/fiat_u64/field.rs: 0/39
|| src/backend/serial/scalar_mul/pippenger.rs: 37/38
|| src/backend/serial/scalar_mul/precomputed_straus.rs: 30/30
|| src/backend/serial/scalar_mul/straus.rs: 28/29
|| src/backend/serial/scalar_mul/variable_base.rs: 17/17
|| src/backend/serial/scalar_mul/vartime_double_base.rs: 24/24
|| src/backend/serial/u32/field.rs: 0/68
|| src/backend/serial/u32/scalar.rs: 0/83
|| src/backend/serial/u64/field.rs: 199/220
|| src/backend/serial/u64/scalar.rs: 148/165
|| src/backend/vector/avx2/edwards.rs: 0/34
|| src/backend/vector/avx2/field.rs: 0/199
|| src/backend/vector/ifma/edwards.rs: 0/34
|| src/backend/vector/ifma/field.rs: 0/328
|| src/backend/vector/scalar_mul/pippenger.rs: 0/40
|| src/backend/vector/scalar_mul/precomputed_straus.rs: 0/27
|| src/backend/vector/scalar_mul/straus.rs: 0/25
|| src/constants.rs: 3/3
|| src/edwards.rs: 162/232
|| src/field.rs: 72/72
|| src/lib.rs: 10/21
|| src/macros.rs: 16/27
|| src/montgomery.rs: 80/90
|| src/ristretto.rs: 197/271
|| src/scalar.rs: 248/287
|| src/traits.rs: 19/20
|| src/window.rs: 48/72
|| 
56.11% coverage, 1589/2832 lines covered
```

**Comment by pinkforest** [comment]
$ `cargo bench --benches`
```
     Running benches/dalek_benchmarks.rs (target/release/deps/dalek_benchmarks-ea776621e6e18e77)
Gnuplot not found, using plotters backend
Scalar inversion        time:   [8.4298 µs 8.4363 µs 8.4438 µs]
Found 14 outliers among 100 measurements (14.00%)
  9 (9.00%) high mild
  5 (5.00%) high severe

batch scalar inversion/Batch scalar inversion/1
                        time:   [8.6897 µs 8.6964 µs 8.7040 µs]
Found 6 outliers among 100 measurements (6.00%)
  5 (5.00%) high mild
  1 (1.00%) high severe
batch scalar inversion/Batch scalar inversion/2
                        time:   [8.8451 µs 8.8498 µs 8.8547 µs]
Found 4 outliers among 100 measurements (4.00%)
  1 (1.00%) high mild
  3 (3.00%) high severe
batch scalar inversion/Batch scalar inversion/4
                        time:   [9.1454 µs 9.1592 µs 9.1750 µs]
Found 10 outliers among 100 measurements (10.00%)
  7 (7.00%) high mild
  3 (3.00%) high severe
batch scalar inversion/Batch scalar inversion/8
                        time:   [9.7435 µs 9.7632 µs 9.7836 µs]
Found 3 outliers among 100 measurements (3.00%)
  1 (1.00%) high mild
  2 (2.00%) high severe
batch scalar inversion/Batch scalar inversion/16
                        time:   [10.900 µs 10.910 µs 10.921 µs]
Found 5 outliers among 100 measurements (5.00%)
  1 (1.00%) low mild
  1 (1.00%) high mild
  3 (3.00%) high severe

Montgomery pseudomultiplication
                        time:   [42.278 µs 42.350 µs 42.447 µs]
Found 8 outliers among 100 measurements (8.00%)
  5 (5.00%) high mild
  3 (3.00%) high severe

RistrettoPoint compression
                        time:   [3.1962 µs 3.1997 µs 3.2034 µs]
Found 3 outliers among 100 measurements (3.00%)
  2 (2.00%) high mild
  1 (1.00%) high severe

RistrettoPoint decompression
                        time:   [3.3114 µs 3.3132 µs 3.3154 µs]
Found 6 outliers among 100 measurements (6.00%)
  5 (5.00%) high mild
  1 (1.00%) high severe

double & compress batched/Batch Ristretto double-and-encode/1
                        time:   [3.2901 µs 3.2949 µs 3.3007 µs]
Found 12 outliers among 100 measurements (12.00%)
  8 (8.00%) high mild
  4 (4.00%) high severe
double & compress batched/Batch Ristretto double-and-encode/2
                        time:   [3.7835 µs 3.7859 µs 3.7885 µs]
Found 14 outliers among 100 measurements (14.00%)
  4 (4.00%) high mild
  10 (10.00%) high severe
double & compress batched/Batch Ristretto double-and-encode/4
                        time:   [4.7848 µs 4.7883 µs 4.7925 µs]
Found 5 outliers among 100 measurements (5.00%)
  4 (4.00%) high mild
  1 (1.00%) high severe
double & compress batched/Batch Ristretto double-and-encode/8
                        time:   [6.9536 µs 6.9768 µs 6.9999 µs]
Found 16 outliers among 100 measurements (16.00%)
  9 (9.00%) low mild
  5 (5.00%) high mild
  2 (2.00%) high severe
double & compress batched/Batch Ristretto double-and-encode/16
                        time:   [11.002 µs 11.076 µs 11.191 µs]
Found 10 outliers among 100 measurements (10.00%)
  2 (2.00%) low mild
  3 (3.00%) high mild
  5 (5.00%) high severe

EdwardsPoint compression
                        time:   [2.7039 µs 2.7104 µs 2.7168 µs]
Found 4 outliers among 100 measurements (4.00%)
  3 (3.00%) high mild
  1 (1.00%) high severe

EdwardsPoint decompression
                        time:   [3.0591 µs 3.0664 µs 3.0739 µs]
Found 3 outliers among 100 measurements (3.00%)
  1 (1.00%) high mild
  2 (2.00%) high severe

Constant-time fixed-base scalar mul
                        time:   [10.784 µs 10.806 µs 10.829 µs]
Found 6 outliers among 100 measurements (6.00%)
  5 (5.00%) high mild
  1 (1.00%) high severe

Constant-time variable-base scalar mul
                        time:   [40.205 µs 40.279 µs 40.356 µs]

Variable-time aA+bB, A variable, B fixed
                        time:   [36.981 µs 37.193 µs 37.430 µs]
Found 6 outliers among 100 measurements (6.00%)
  6 (6.00%) high mild

Multiscalar multiplications/Constant-time variable-base multiscalar multiplication/1
                        time:   [42.844 µs 43.047 µs 43.221 µs]
Multiscalar multiplications/Constant-time variable-base multiscalar multiplication/2
                        time:   [57.099 µs 57.377 µs 57.671 µs]
Multiscalar multiplications/Constant-time variable-base multiscalar multiplication/4
                        time:   [85.820 µs 86.911 µs 88.727 µs]
Found 1 outliers among 15 measurements (6.67%)
  1 (6.67%) high severe
Multiscalar multiplications/Constant-time variable-base multiscalar multiplication/8
                        time:   [141.98 µs 142.92 µs 144.24 µs]
Multiscalar multiplications/Constant-time variable-base multiscalar multiplication/16
                        time:   [255.50 µs 256.32 µs 257.28 µs]
Found 2 outliers among 15 measurements (13.33%)
  1 (6.67%) low mild
  1 (6.67%) high mild
Multiscalar multiplications/Constant-time variable-base multiscalar multiplication/32
                        time:   [480.77 µs 482.45 µs 484.37 µs]
Found 1 outliers among 15 measurements (6.67%)
  1 (6.67%) high mild
Multiscalar multiplications/Constant-time variable-base multiscalar multiplication/64
                        time:   [927.01 µs 929.99 µs 933.95 µs]
Found 1 outliers among 15 measurements (6.67%)
  1 (6.67%) high severe
Multiscalar multiplications/Constant-time variable-base multiscalar multiplication/128
                        time:   [1.8289 ms 1.8340 ms 1.8403 ms]
Found 2 outliers among 15 measurements (13.33%)
  2 (13.33%) high mild
Multiscalar multiplications/Constant-time variable-base multiscalar multiplication/256
                        time:   [3.6567 ms 3.6942 ms 3.7345 ms]
Multiscalar multiplications/Constant-time variable-base multiscalar multiplication/384
                        time:   [5.4620 ms 5.4915 ms 5.5227 ms]
Found 1 outliers among 15 measurements (6.67%)
  1 (6.67%) low mild
Multiscalar multiplications/Constant-time variable-base multiscalar multiplication/512
                        time:   [7.3185 ms 7.3547 ms 7.3969 ms]
Found 1 outliers among 15 measurements (6.67%)
  1 (6.67%) low mild
Multiscalar multiplications/Constant-time variable-base multiscalar multiplication/768
                        time:   [10.877 ms 10.887 ms 10.896 ms]
Found 3 outliers among 15 measurements (20.00%)
  2 (13.33%) low severe
  1 (6.67%) high severe
Multiscalar multiplications/Constant-time variable-base multiscalar multiplication/1024
                        time:   [14.594 ms 14.678 ms 14.793 ms]
Found 2 outliers among 15 measurements (13.33%)
  1 (6.67%) low mild
  1 (6.67%) high mild
Multiscalar multiplications/Variable-time variable-base multiscalar multiplication/1
                        time:   [34.812 µs 35.111 µs 35.452 µs]
Multiscalar multiplications/Variable-time variable-base multiscalar multiplication/2
                        time:   [42.493 µs 42.668 µs 42.876 µs]
Found 2 outliers among 15 measurements (13.33%)
  2 (13.33%) high mild
Multiscalar multiplications/Variable-time variable-base multiscalar multiplication/4
                        time:   [58.261 µs 58.465 µs 58.718 µs]
Multiscalar multiplications/Variable-time variable-base multiscalar multiplication/8
                        time:   [90.449 µs 91.102 µs 91.693 µs]
Multiscalar multiplications/Variable-time variable-base multiscalar multiplication/16
                        time:   [153.80 µs 154.37 µs 155.35 µs]
Multiscalar multiplications/Variable-time variable-base multiscalar multiplication/32
                        time:   [284.94 µs 287.02 µs 288.09 µs]
Multiscalar multiplications/Variable-time variable-base multiscalar multiplication/64
                        time:   [534.62 µs 536.52 µs 539.00 µs]
Found 2 outliers among 15 measurements (13.33%)
  1 (6.67%) high mild
  1 (6.67%) high severe
Multiscalar multiplications/Variable-time variable-base multiscalar multiplication/128
                        time:   [1.0688 ms 1.0793 ms 1.0893 ms]
Multiscalar multiplications/Variable-time variable-base multiscalar multiplication/256
                        time:   [1.9952 ms 2.0011 ms 2.0124 ms]
Found 1 outliers among 15 measurements (6.67%)
  1 (6.67%) high severe
Multiscalar multiplications/Variable-time variable-base multiscalar multiplication/384
                        time:   [2.7674 ms 2.7740 ms 2.7835 ms]
Found 4 outliers among 15 measurements (26.67%)
  1 (6.67%) low mild
  2 (13.33%) high mild
  1 (6.67%) high severe
Multiscalar multiplications/Variable-time variable-base multiscalar multiplication/512
                        time:   [3.4732 ms 3.4911 ms 3.5044 ms]
Multiscalar multiplications/Variable-time variable-base multiscalar multiplication/768
                        time:   [4.8157 ms 4.8301 ms 4.8513 ms]
Found 1 outliers among 15 measurements (6.67%)
  1 (6.67%) high mild
Multiscalar multiplications/Variable-time variable-base multiscalar multiplication/1024
                        time:   [6.1005 ms 6.1092 ms 6.1164 ms]
Found 3 outliers among 15 measurements (20.00%)
  1 (6.67%) low severe
  2 (13.33%) high mild
Multiscalar multiplications/Variable-time fixed-base multiscalar multiplication/1
                        time:   [32.252 µs 32.282 µs 32.314 µs]
Found 1 outliers among 15 measurements (6.67%)
  1 (6.67%) low mild
Multiscalar multiplications/Variable-time fixed-base multiscalar multiplication/2
                        time:   [38.453 µs 38.703 µs 38.935 µs]
Multiscalar multiplications/Variable-time fixed-base multiscalar multiplication/4
                        time:   [50.447 µs 50.561 µs 50.706 µs]
Found 1 outliers among 15 measurements (6.67%)
  1 (6.67%) high mild
Multiscalar multiplications/Variable-time fixed-base multiscalar multiplication/8
                        time:   [75.231 µs 76.019 µs 77.015 µs]
Found 2 outliers among 15 measurements (13.33%)
  2 (13.33%) high mild
Multiscalar multiplications/Variable-time fixed-base multiscalar multiplication/16
                        time:   [121.53 µs 121.67 µs 121.88 µs]
Found 1 outliers among 15 measurements (6.67%)
  1 (6.67%) high severe
Multiscalar multiplications/Variable-time fixed-base multiscalar multiplication/32
                        time:   [217.29 µs 218.29 µs 219.43 µs]
Found 1 outliers among 15 measurements (6.67%)
  1 (6.67%) high mild
Multiscalar multiplications/Variable-time fixed-base multiscalar multiplication/64
                        time:   [407.21 µs 407.67 µs 408.42 µs]
Found 1 outliers among 15 measurements (6.67%)
  1 (6.67%) high mild
Multiscalar multiplications/Variable-time fixed-base multiscalar multiplication/128
                        time:   [797.48 µs 798.33 µs 798.91 µs]
Found 2 outliers among 15 measurements (13.33%)
  1 (6.67%) low mild
  1 (6.67%) high mild
Multiscalar multiplications/Variable-time fixed-base multiscalar multiplication/256
                        time:   [1.5845 ms 1.5934 ms 1.6031 ms]
Found 1 outliers among 15 measurements (6.67%)
  1 (6.67%) high mild
Multiscalar multiplications/Variable-time fixed-base multiscalar multiplication/384
                        time:   [2.3829 ms 2.3869 ms 2.3905 ms]
Found 1 outliers among 15 measurements (6.67%)
  1 (6.67%) high mild
Multiscalar multiplications/Variable-time fixed-base multiscalar multiplication/512
                        time:   [3.1753 ms 3.1801 ms 3.1856 ms]
Multiscalar multiplications/Variable-time fixed-base multiscalar multiplication/768
                        time:   [4.7811 ms 4.7875 ms 4.7934 ms]
Found 1 outliers among 15 measurements (6.67%)
  1 (6.67%) high severe
Multiscalar multiplications/Variable-time fixed-base multiscalar multiplication/1024
                        time:   [6.4286 ms 6.4367 ms 6.4422 ms]
Found 1 outliers among 15 measurements (6.67%)
  1 (6.67%) high severe
Multiscalar multiplications/Variable-time mixed-base/(size: 1), (0pct dyn)
                        time:   [32.195 µs 32.224 µs 32.267 µs]
Multiscalar multiplications/Variable-time mixed-base/(size: 2), (0pct dyn)
                        time:   [38.370 µs 38.438 µs 38.504 µs]
Multiscalar multiplications/Variable-time mixed-base/(size: 4), (0pct dyn)
                        time:   [50.260 µs 50.333 µs 50.424 µs]
Found 1 outliers among 15 measurements (6.67%)
  1 (6.67%) high mild
Multiscalar multiplications/Variable-time mixed-base/(size: 8), (0pct dyn)
                        time:   [75.089 µs 75.378 µs 75.661 µs]
Multiscalar multiplications/Variable-time mixed-base/(size: 16), (0pct dyn)
                        time:   [122.75 µs 123.32 µs 123.96 µs]
Found 1 outliers among 15 measurements (6.67%)
  1 (6.67%) high mild
Multiscalar multiplications/Variable-time mixed-base/(size: 32), (0pct dyn)
                        time:   [216.79 µs 217.09 µs 217.47 µs]
Found 2 outliers among 15 measurements (13.33%)
  1 (6.67%) high mild
  1 (6.67%) high severe
Multiscalar multiplications/Variable-time mixed-base/(size: 64), (0pct dyn)
                        time:   [407.42 µs 409.64 µs 413.78 µs]
Found 1 outliers among 15 measurements (6.67%)
  1 (6.67%) high severe
Multiscalar multiplications/Variable-time mixed-base/(size: 128), (0pct dyn)
                        time:   [795.23 µs 795.66 µs 796.39 µs]
Found 1 outliers among 15 measurements (6.67%)
  1 (6.67%) high mild
Multiscalar multiplications/Variable-time mixed-base/(size: 256), (0pct dyn)
                        time:   [1.5828 ms 1.5862 ms 1.5891 ms]
Found 2 outliers among 15 measurements (13.33%)
  2 (13.33%) high mild
Multiscalar multiplications/Variable-time mixed-base/(size: 384), (0pct dyn)
                        time:   [2.4159 ms 2.4269 ms 2.4401 ms]
Multiscalar multiplications/Variable-time mixed-base/(size: 512), (0pct dyn)
                        time:   [3.2018 ms 3.2304 ms 3.2793 ms]
Found 1 outliers among 15 measurements (6.67%)
  1 (6.67%) high severe
Multiscalar multiplications/Variable-time mixed-base/(size: 768), (0pct dyn)
                        time:   [4.8166 ms 4.8614 ms 4.8915 ms]
Multiscalar multiplications/Variable-time mixed-base/(size: 1024), (0pct dyn)
                        time:   [6.4078 ms 6.4118 ms 6.4155 ms]
Found 2 outliers among 15 measurements (13.33%)
  1 (6.67%) low mild
  1 (6.67%) high mild
Multiscalar multiplications/Variable-time mixed-base/(size: 1), (20pct dyn)
                        time:   [32.214 µs 32.243 µs 32.262 µs]
Multiscalar multiplications/Variable-time mixed-base/(size: 2), (20pct dyn)
                        time:   [38.353 µs 38.436 µs 38.541 µs]
Found 1 outliers among 15 measurements (6.67%)
  1 (6.67%) high mild
Multiscalar multiplications/Variable-time mixed-base/(size: 4), (20pct dyn)
                        time:   [50.233 µs 50.299 µs 50.363 µs]
Found 3 outliers among 15 measurements (20.00%)
  2 (13.33%) high mild
  1 (6.67%) high severe
Multiscalar multiplications/Variable-time mixed-base/(size: 8), (20pct dyn)
                        time:   [76.267 µs 76.419 µs 76.635 µs]
Found 2 outliers among 15 measurements (13.33%)
  1 (6.67%) high mild
  1 (6.67%) high severe
Multiscalar multiplications/Variable-time mixed-base/(size: 16), (20pct dyn)
                        time:   [128.47 µs 128.58 µs 128.67 µs]
Multiscalar multiplications/Variable-time mixed-base/(size: 32), (20pct dyn)
                        time:   [230.28 µs 230.98 µs 231.85 µs]
Found 2 outliers among 15 measurements (13.33%)
  2 (13.33%) high mild
Multiscalar multiplications/Variable-time mixed-base/(size: 64), (20pct dyn)
                        time:   [433.13 µs 433.48 µs 434.00 µs]
Found 1 outliers among 15 measurements (6.67%)
  1 (6.67%) high mild
Multiscalar multiplications/Variable-time mixed-base/(size: 128), (20pct dyn)
                        time:   [847.63 µs 848.26 µs 849.11 µs]
Found 1 outliers among 15 measurements (6.67%)
  1 (6.67%) high mild
Multiscalar multiplications/Variable-time mixed-base/(size: 256), (20pct dyn)
                        time:   [1.6824 ms 1.6835 ms 1.6852 ms]
Multiscalar multiplications/Variable-time mixed-base/(size: 384), (20pct dyn)
                        time:   [2.5236 ms 2.5289 ms 2.5350 ms]
Found 1 outliers among 15 measurements (6.67%)
  1 (6.67%) high severe
Multiscalar multiplications/Variable-time mixed-base/(size: 512), (20pct dyn)
                        time:   [3.3745 ms 3.3864 ms 3.4027 ms]
Found 1 outliers among 15 measurements (6.67%)
  1 (6.67%) high severe
Multiscalar multiplications/Variable-time mixed-base/(size: 768), (20pct dyn)
                        time:   [5.1715 ms 5.1934 ms 5.2096 ms]
Multiscalar multiplications/Variable-time mixed-base/(size: 1024), (20pct dyn)
                        time:   [6.9178 ms 6.9369 ms 6.9594 ms]
Multiscalar multiplications/Variable-time mixed-base/(size: 1), (50pct dyn)
                        time:   [32.323 µs 32.403 µs 32.538 µs]
Multiscalar multiplications/Variable-time mixed-base/(size: 2), (50pct dyn)
                        time:   [40.339 µs 40.381 µs 40.449 µs]
Found 1 outliers among 15 measurements (6.67%)
  1 (6.67%) high mild
Multiscalar multiplications/Variable-time mixed-base/(size: 4), (50pct dyn)
                        time:   [54.654 µs 54.904 µs 55.220 µs]
Multiscalar multiplications/Variable-time mixed-base/(size: 8), (50pct dyn)
                        time:   [82.878 µs 83.382 µs 83.890 µs]
Found 1 outliers among 15 measurements (6.67%)
  1 (6.67%) high mild
Multiscalar multiplications/Variable-time mixed-base/(size: 16), (50pct dyn)
                        time:   [139.17 µs 140.79 µs 142.99 µs]
Found 1 outliers among 15 measurements (6.67%)
  1 (6.67%) high severe
Multiscalar multiplications/Variable-time mixed-base/(size: 32), (50pct dyn)
                        time:   [252.32 µs 254.07 µs 255.59 µs]
Multiscalar multiplications/Variable-time mixed-base/(size: 64), (50pct dyn)
                        time:   [473.31 µs 475.70 µs 479.18 µs]
Found 1 outliers among 15 measurements (6.67%)
  1 (6.67%) high severe
Multiscalar multiplications/Variable-time mixed-base/(size: 128), (50pct dyn)
                        time:   [933.39 µs 937.76 µs 941.56 µs]
Multiscalar multiplications/Variable-time mixed-base/(size: 256), (50pct dyn)
                        time:   [1.8527 ms 1.8613 ms 1.8683 ms]
Found 1 outliers among 15 measurements (6.67%)
  1 (6.67%) high mild
Multiscalar multiplications/Variable-time mixed-base/(size: 384), (50pct dyn)
                        time:   [2.7704 ms 2.7736 ms 2.7770 ms]
Multiscalar multiplications/Variable-time mixed-base/(size: 512), (50pct dyn)
                        time:   [3.7256 ms 3.7429 ms 3.7694 ms]
Found 1 outliers among 15 measurements (6.67%)
  1 (6.67%) high severe
Multiscalar multiplications/Variable-time mixed-base/(size: 768), (50pct dyn)
                        time:   [5.5937 ms 5.6098 ms 5.6284 ms]
Found 1 outliers among 15 measurements (6.67%)
  1 (6.67%) high mild
Multiscalar multiplications/Variable-time mixed-base/(size: 1024), (50pct dyn)
                        time:   [7.5290 ms 7.5752 ms 7.6480 ms]
Found 1 outliers among 15 measurements (6.67%)
  1 (6.67%) high mild
```

**Comment by rozbb** [comment]
Nice! One question: why is `default-features = false` necessary? It looks like that omits the `cargo_bench_support` feature. Do we not want that?

**Comment by pinkforest** [comment]
Yeah I don't think it is necessary to get rid of the csv - srde_cbor -> ciborium is regardless I know - let me test and fix that

**Comment by pinkforest** [comment]
tarpaulin:
56.02% coverage, 1582/2824 lines covered
benches:
TBD: running

**Comment by rozbb** [comment]
Ok cool. Last thing: could you remove the `plotters` feature, since it's already default? I'd do it myself but I just spent the last 10min fighting Github permissions on editing this PR

**Comment by pinkforest** [comment]
Yeah was going to do that, done :)

**Comment by rozbb** [comment]
Awesome, thanks so much!

**Pull request merged**
