### PR TITLE
ed25519-dalek: fixup pkcs8 API break

### PR DESCRIPTION
**Pull request by baloo**
targets #676

### CODE REVIEW

**Comment by tarcieri** [comment]
@baloo needs a clippy bump

**Comment by tarcieri** [comment]
Hmm, perhaps temporarily disable clippy until we can get all of those failures resolved: https://github.com/dalek-cryptography/curve25519-dalek/actions/runs/11112946832/job/30876334749?pr=709

**Comment by tarcieri** [comment]
Would be great if you could cherry-pick 3b21376 into a separate PR

**Comment by baloo** [comment]
> Would be great if you could cherry-pick [3b21376](https://github.com/dalek-cryptography/curve25519-dalek/commit/3b21376d637ddfbc89e6559853db15d564f9425f) into a separate PR (it's fine to have in this one for now, too)

https://github.com/dalek-cryptography/curve25519-dalek/pull/710

**Pull request merged**
