### PR TITLE
Update dependencies, move to 2021 edition

### PR DESCRIPTION
**Pull request by rickwebiii**
Update crate to 2021 edition (just had to fix crate paths) and update dependencies.

### CODE REVIEW

**Review by ethyi — APPROVED** [review]
No changes to tests, logic, just better and more flexible versioning, especially for zeroize.

All tests pass.

Please merge, inflexible versioning leads to difficult versioning conflicts down the line, and Rust currently doesn't have the right tooling to work around it.

**Comment by rickwebiii** [comment]
@ethyi I need someone to click "Approve and Run" as this is my first contribution here.

**Review by ethyi — COMMENTED** [review]
It could be better to specify zeroize with "1.0.0" since it will be compatible with anything above "1.0", including "1.5.7". Same applies for other major release crates.

**Comment by rickwebiii** [comment]
@ethyi I did some investigation as to why they were using zeroize >=1.0, <1.4 and it appears to be to maintain compatibility with Rust toolchain 1.41 for some downstream dependencies. I'm not sure if this is still a requirement or not, @isislovecruft could provide some insight as they made the change.

**Comment by rozbb** [comment]
Resolved in `release/4.0` branch

**Pull request closed without merging**
